//! Access to the node bytes embedded at build time.
//!
//! Production reads constants emitted by `build.rs` into
//! `$OUT_DIR/node_meta.rs`. When `AIONUI_EMBED_NODE` is unset at build time,
//! `build.rs` emits a stub with `HAS_EMBEDDED_NODE = false`, which makes
//! `resolve_node()` fall back to `which()` — exactly the pre-embed behavior.

/// Raw compile-time constants generated by `build.rs` into
/// `$OUT_DIR/node_meta.rs`.
pub(crate) mod node_consts {
    include!(concat!(env!("OUT_DIR"), "/node_meta.rs"));
}

/// Indirection trait for the bundled node blob — allows tests to inject a
/// fake embedded payload instead of linking the real (potentially large)
/// compressed blob.
pub trait EmbeddedNode: Send + Sync {
    fn has(&self) -> bool;
    fn blob(&self) -> &'static [u8];
    fn sha256(&self) -> &'static str;
    fn version(&self) -> &'static str;
    /// Stable directory name `node-<version>-<sha12>` derived at build time.
    #[allow(dead_code)]
    fn dir_name(&self) -> &'static str;
}

#[derive(Debug, Default, Clone, Copy)]
pub struct ProductionEmbedNode;

impl EmbeddedNode for ProductionEmbedNode {
    fn has(&self) -> bool {
        node_consts::HAS_EMBEDDED_NODE
    }
    fn blob(&self) -> &'static [u8] {
        node_consts::NODE_BLOB
    }
    fn sha256(&self) -> &'static str {
        node_consts::NODE_SHA256
    }
    fn version(&self) -> &'static str {
        node_consts::NODE_VERSION
    }
    fn dir_name(&self) -> &'static str {
        node_consts::NODE_DIR_NAME
    }
}

#[cfg(test)]
pub(crate) struct FakeEmbedNode {
    pub has: bool,
    pub blob: &'static [u8],
    pub sha256: &'static str,
    pub version: &'static str,
    pub dir_name: &'static str,
}

#[cfg(test)]
impl EmbeddedNode for FakeEmbedNode {
    fn has(&self) -> bool {
        self.has
    }
    fn blob(&self) -> &'static [u8] {
        self.blob
    }
    fn sha256(&self) -> &'static str {
        self.sha256
    }
    fn version(&self) -> &'static str {
        self.version
    }
    fn dir_name(&self) -> &'static str {
        self.dir_name
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn production_embed_node_respects_env_gate() {
        assert!(!ProductionEmbedNode.has());
        assert_eq!(ProductionEmbedNode.blob(), b"");
    }

    #[test]
    fn fake_embed_node_returns_injected_values() {
        let fake = FakeEmbedNode {
            has: true,
            blob: b"hello",
            sha256: "deadbeef",
            version: "22.11.0",
            dir_name: "node-22.11.0-deadbeef0000",
        };
        assert!(fake.has());
        assert_eq!(fake.blob(), b"hello");
        assert_eq!(fake.sha256(), "deadbeef");
        assert_eq!(fake.version(), "22.11.0");
        assert_eq!(fake.dir_name(), "node-22.11.0-deadbeef0000");
    }
}
