//! Build-time bundling of the node runtime.
//!
//! - Reads `NODE_VERSION_OVERRIDE` env (or falls back to
//!   `[package.metadata.aionui-runtime] node_version` from Cargo.toml).
//! - When `AIONUI_EMBED_NODE=1` and the target has a known asset:
//!   downloads `node-v<ver>-<platform>-<arch>.tar.xz` (or `.zip` on
//!   Windows), repacks the tree as a zstd+tar blob, and emits constants
//!   into `$OUT_DIR/node_meta.rs`.
//! - Otherwise emits a stub `node_meta.rs` with `HAS_EMBEDDED_NODE = false`.
//! - Caches decompressed + repacked artifacts in
//!   `$CARGO_HOME/aionui-node-cache/`.

#[path = "build_support.rs"]
mod build_support;

use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

fn main() {
    // Always emit a node_meta.rs stub so src/embed.rs compiles when
    // AIONUI_EMBED_NODE is unset. Real population happens when the flag is set.
    let node_meta_path = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("node_meta.rs");
    if !node_meta_path.is_file() {
        let stub_blob = node_meta_path.parent().unwrap().join("node.blob.zst.tar");
        if !stub_blob.is_file() {
            std::fs::write(&stub_blob, []).expect("write stub node blob");
        }
        let body = "// @generated by build.rs — stub\n\
                    pub const NODE_BLOB: &[u8] = include_bytes!(\"node.blob.zst.tar\");\n\
                    pub const NODE_SHA256: &str = \"\";\n\
                    pub const NODE_VERSION: &str = \"\";\n\
                    #[allow(dead_code)]\n\
                    pub const NODE_DIR_NAME: &str = \"\";\n\
                    pub const HAS_EMBEDDED_NODE: bool = false;\n";
        std::fs::write(&node_meta_path, body).expect("write stub node_meta.rs");
    }

    println!("cargo:rerun-if-env-changed=AIONUI_EMBED_NODE");
    println!("cargo:rerun-if-env-changed=NODE_VERSION_OVERRIDE");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build_support.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");

    let target = std::env::var("TARGET").expect("TARGET env set by cargo");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));

    embed_node(&target, &out_dir);
}

fn read_node_version() -> String {
    if let Ok(v) = std::env::var("NODE_VERSION_OVERRIDE")
        && !v.trim().is_empty()
    {
        return v;
    }
    let toml_src = fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let parsed: toml::Value = toml::from_str(&toml_src).expect("parse Cargo.toml");
    parsed
        .get("package")
        .and_then(|p| p.get("metadata"))
        .and_then(|m| m.get("aionui-runtime"))
        .and_then(|r| r.get("node_version"))
        .and_then(|v| v.as_str())
        .expect("[package.metadata.aionui-runtime] node_version missing")
        .to_string()
}

fn cargo_node_cache_root() -> PathBuf {
    let home = std::env::var("CARGO_HOME").map(PathBuf::from).unwrap_or_else(|_| {
        dirs::home_dir()
            .map(|h| h.join(".cargo"))
            .unwrap_or_else(|| PathBuf::from(".cargo"))
    });
    home.join("aionui-node-cache")
}

fn embed_node(target: &str, out_dir: &Path) {
    let meta_path = out_dir.join("node_meta.rs");

    if std::env::var("AIONUI_EMBED_NODE").as_deref() != Ok("1") {
        return; // stub already written at top of main()
    }
    if !build_support::has_embedded_node(target) {
        return;
    }
    let Some(asset_template) = build_support::node_asset_for_target(target) else {
        println!("cargo:warning=No node asset mapped for target {target}");
        return;
    };

    let version = read_node_version();
    let asset = asset_template.replace("{ver}", &version);
    let cache_root = cargo_node_cache_root().join(&version).join(target);
    fs::create_dir_all(&cache_root).expect("create node cache dir");

    let archive_path = cache_root.join(&asset);
    let unpack_dir = cache_root.join("unpacked");
    let blob_path = cache_root.join("node.blob.zst.tar");
    let sha_path = cache_root.join("node.sha256");

    if !archive_path.is_file() {
        let url = build_support::node_download_url(&version, &asset);
        println!("cargo:info=Downloading {url}");
        download(&url, &archive_path);
    }
    if !unpack_dir.is_dir() {
        unpack_node_archive(&archive_path, &unpack_dir);
    }

    if !blob_path.is_file() {
        repack_as_zstd_tar(&unpack_dir, &blob_path);
    }

    let sha_hex = if sha_path.is_file() {
        fs::read_to_string(&sha_path).expect("read sha").trim().to_string()
    } else {
        let hex = sha256_of(&blob_path);
        fs::write(&sha_path, &hex).expect("write sha");
        hex
    };

    fs::copy(&blob_path, out_dir.join("node.blob.zst.tar")).expect("copy node blob to OUT_DIR");

    let dir_name = build_support::node_dir_name(&version, &sha_hex);
    let meta = format!(
        "// @generated by build.rs — do not edit\n\
         pub const NODE_BLOB: &[u8] = include_bytes!(\"node.blob.zst.tar\");\n\
         pub const NODE_SHA256: &str = \"{sha_hex}\";\n\
         pub const NODE_VERSION: &str = \"{version}\";\n\
         pub const NODE_DIR_NAME: &str = \"{dir_name}\";\n\
         pub const HAS_EMBEDDED_NODE: bool = true;\n"
    );
    fs::write(&meta_path, meta).expect("write node_meta.rs");
}

fn download(url: &str, out: &Path) {
    let bytes = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(600))
        .build()
        .expect("build http client")
        .get(url)
        .send()
        .unwrap_or_else(|e| panic!("GET {url} failed: {e}"))
        .error_for_status()
        .unwrap_or_else(|e| panic!("non-2xx from {url}: {e}"))
        .bytes()
        .unwrap_or_else(|e| panic!("read body: {e}"));
    fs::write(out, &bytes).unwrap_or_else(|e| panic!("write {}: {e}", out.display()));
}

fn unpack_node_archive(archive: &Path, dest: &Path) {
    fs::create_dir_all(dest).expect("create unpack dir");
    let name = archive.file_name().unwrap().to_string_lossy().into_owned();
    let f = fs::File::open(archive).expect("open archive");
    if name.ends_with(".tar.xz") {
        let dec = xz2::read::XzDecoder::new(f);
        let mut tar = tar::Archive::new(dec);
        tar.set_preserve_permissions(true);
        tar.unpack(dest).expect("unpack tar.xz");
    } else if name.ends_with(".tar.gz") {
        let dec = flate2::read::GzDecoder::new(f);
        let mut tar = tar::Archive::new(dec);
        tar.set_preserve_permissions(true);
        tar.unpack(dest).expect("unpack tar.gz");
    } else if name.ends_with(".zip") {
        let mut archive = zip::ZipArchive::new(f).expect("read node zip");
        archive.extract(dest).expect("extract node zip");
    } else {
        panic!("unknown node archive extension: {name}");
    }
}

fn repack_as_zstd_tar(unpacked: &Path, out: &Path) {
    // Walk into the single top-level dir node-* and re-pack its contents
    // (so on-disk extract drops directly into <data_dir>/node-{ver}-{sha}/).
    let top = fs::read_dir(unpacked)
        .expect("read unpack")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .find(|p| {
            p.is_dir()
                && p.file_name()
                    .and_then(|n| n.to_str())
                    .is_some_and(|n| n.starts_with("node-"))
        })
        .expect("node-* top-level dir");

    let f = fs::File::create(out).expect("create blob");
    let enc = zstd::stream::write::Encoder::new(f, 19).expect("zstd encoder");
    let mut tar_writer = tar::Builder::new(enc);
    tar_writer.follow_symlinks(false); // keep `npm` -> `../lib/...` symlinks
    tar_writer.append_dir_all(".", &top).expect("append node tree");
    let enc = tar_writer.into_inner().expect("finish tar");
    enc.finish().expect("finish zstd");
}

fn sha256_of(path: &Path) -> String {
    let mut f = fs::File::open(path).expect("open for sha");
    let mut hasher = Sha256::new();
    let mut buf = [0u8; 64 * 1024];
    loop {
        let n = f.read(&mut buf).expect("read chunk");
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    hex::encode(hasher.finalize())
}
